# Generated by Django 3.2.8 on 2021-10-30 03:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0003_alter_card_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='data_criacao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='data_modificacao',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
