# Generated by Django 3.2.8 on 2021-10-30 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_auto_20211030_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='card.tag', verbose_name='tags'),
        ),
    ]
