# Generated by Django 3.2.8 on 2021-10-30 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.tag', verbose_name='tags'),
        ),
    ]
